# version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: meduse_web
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"  # Utilisation d'un port non conventionnel pour le serveur web
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: meduse_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: meduse_db
      MYSQL_USER: meduse_user
      MYSQL_PASSWORD: meduse_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "9906:3306"  # Utilisation d'un port non conventionnel pour MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meduse_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"  # Utilisation d'un port non conventionnel pour phpMyAdmin

volumes:
  db_data:
