# config/routes.yaml

default:
    path: /default
    controller: App\Controller\DefaultController::default

index:
    path: /
    controller: App\Controller\HomeController::index

sign_up:
    path: /sign/up
    controller: App\Controller\SignUpController::index

sign_in:
    path: /sign/in
    controller: App\Controller\SignInController::index

reset1:
    path: /reset1
    controller: App\Controller\Reset1Controller::index

reset2:
    path: /reset2
    controller: App\Controller\Reset2Controller::index

terms_condition:
    path: /terms_condition
    controller: App\Controller\TermsConditionController::index

logout:
    path: /logout




# Liens outil EMaker
episode_index:
    path: /tool_emaker
    controller: App\Controller\EpisodeMakerController::index
    methods: GET

episode_new:
    path: /tool_emaker/new
    controller: App\Controller\EpisodeMakerController::new
    methods: [GET, POST]

episode_edit:
    path: /tool_emaker/edit/{id}
    controller: App\Controller\EpisodeMakerController::edit
    methods: [GET, POST]

episode_delete:
    path: /tool_emaker/delete/{id}
    controller: App\Controller\EpisodeMakerController::delete
    methods: POST
# ******************





# noti_file_index:
#     path: /noti-file
#     controller: App\Controller\NotiFileController::index
#     methods: GET

# noti_file_new:
#     path: /noti-file/new
#     controller: App\Controller\NotiFileController::new
#     methods: [GET, POST]

# noti_file_edit:
#     path: /noti-file/edit/{id}
#     controller: App\Controller\NotiFileController::edit
#     methods: [GET, POST]

# noti_file_delete:
#     path: /noti-file/delete/{id}
#     controller: App\Controller\NotiFileController::delete
#     methods: POST

# noti_file_archive:
#     path: /noti-file/archive/{id}
#     controller: App\Controller\NotiFileController::archive
#     methods: POST

# noti_file_download:
#     path: /noti-file/download/{id}
#     controller: App\Controller\NotiFileController::download
#     methods: GET


# controllers:
#     resource: ../src/Controller/
#     type: attribute

# notifile:
#     path: /notifile
#     controller: App\Controller\NotiFileController

notifile:
    resource: ../src/Controller/NotiFileController.php
    type: annotation

notifile_edit:
    path: /notifile/edit/{id}
    controller: App\Controller\NotiFileController::edit

notifile_download:
    path: /notifile/download/{id}
    controller: App\Controller\NotiFileController::download

notifile_index:
    path: /notifile
    controller: App\Controller\NotiFileController::index

notifile_new:
    path: /notifile/new
    controller: App\Controller\NotiFileController::new

notifile_show:
    path: /notifile/show/{id}
    controller: App\Controller\NotiFileController::show

notifile_delete:
    path: /notifile/delete/{id}
    controller: App\Controller\NotiFileController::delete
    methods: POST





