# config/routes.yaml

default:
    path: /default
    controller: App\Controller\DefaultController::default

index:
    path: /
    controller: App\Controller\HomeController::index

sign_up:
    path: /sign/up
    controller: App\Controller\SignUpController::index

sign_in:
    path: /sign/in
    controller: App\Controller\SignInController::index

reset1:
    path: /reset1
    controller: App\Controller\Reset1Controller::index

reset2:
    path: /reset2
    controller: App\Controller\Reset2Controller::index

terms_condition:
    path: /terms_condition
    controller: App\Controller\TermsConditionController::index

logout:
    path: /logout

member_area:
    path: /member_area
    controller: App\Controller\MemberAreaController::index
